# Generated by Django 5.1.5 on 2025-09-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsTurmsek', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=999)),
                ('tankType', models.CharField(max_length=99)),
                ('OnoTogoStoit', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('IsPonerflenVHlam', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=9999)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
