# Generated by Django 5.1.5 on 2025-10-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'мой тунк', 'verbose_name_plural': 'мои тунчеки'},
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='IsPonerflenVHlam',
            field=models.BooleanField(default=True, verbose_name='Понерфлен ли улиткой в хлам'),
        ),
        migrations.AlterField(
            model_name='item',
            name='IsTurmsek',
            field=models.BooleanField(default=False, verbose_name='турмс или не турмс вот в чем вопрос'),
        ),
        migrations.AlterField(
            model_name='item',
            name='OnoTogoStoit',
            field=models.BooleanField(default=False, verbose_name='стоит ли брать'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ценна в рублях'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(verbose_name='дата выхода танка в реальности'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=9999, verbose_name='опИсание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='количество пакетиков с танком'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tankType',
            field=models.CharField(max_length=99, verbose_name='тип тунка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=999, verbose_name='Название'),
        ),
    ]
