# Generated by Django 5.1.5 on 2025-10-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_options_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='imgs/default.png', null=True, upload_to='imgs/'),
        ),
    ]
